### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by zDream** [macrozheng/springcloud-learning#29]
Internal error (java.nio.file.InvalidPathException): Illegal char <?> at index 3: D:/?ideaWork/springcloud-learning
java.nio.file.InvalidPathException: Illegal char <?> at index 3: D:/?ideaWork/springcloud-learning
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.jetbrains.jps.model.serialization.JpsProjectLoader.loadProject(JpsProjectLoader.java:93)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:24)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:34)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:68)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:324)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:175)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$15/186370494.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

![image](https://user-images.githubusercontent.com/16067566/187176915-b292344f-f145-4f1d-8c17-ccfe76009f90.png)
nfty
导入后报了这个错，有遇见的吗

**Comment by zDream** [comment]
已解决，是我目录的问题，不知道为什么多了个空格
